In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('../data/logistic.csv')

Xdf = df[['score', 'attitude']]
Ydf = df['status']

X = np.array(Xdf).reshape(-1, 2).astype('float64')
Y = np.array(Ydf).reshape(-1, 1).astype('float64')

In [3]:
print(Xdf)

   score  attitude
0     90        80
1     87        30
2    100        90
3     78        90
4     75        90
5     74        60
6     70        90
7     50        98
8     20        90


In [4]:
print(X, X.shape)

[[ 90.  80.]
 [ 87.  30.]
 [100.  90.]
 [ 78.  90.]
 [ 75.  90.]
 [ 74.  60.]
 [ 70.  90.]
 [ 50.  98.]
 [ 20.  90.]] (9, 2)


In [5]:
n = X.shape[1]
weight = np.ones(n)
print(weight, weight.shape)

[1. 1.] (2,)


In [6]:
arr = np.array([[2], [0]])
print(arr.shape)
print(arr)

(2, 1)
[[2]
 [0]]


In [7]:
weight = arr
multi = np.dot(X, weight)
print(multi)
print(multi.shape)

[[180.]
 [174.]
 [200.]
 [156.]
 [150.]
 [148.]
 [140.]
 [100.]
 [ 40.]]
(9, 1)


In [8]:
df = pd.read_csv('../data/logistic.csv')

Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

model = LogisticRegression()
model.train(x, y, 10000, 0.0001)
ypred = model.predict(90, 80) 

NameError: name 'LogisticRegression' is not defined

In [ ]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

print(x, x.shape)
print(y, y.shape)

print(50* "=")
Pre = lambda za: 1 / (1 + np.exp(-za))
m, n = x.shape
print(f"m: {m}\nn: {n}")
lr = 0.0001

weight = np.zeros(n)
weight = np.array(weight).reshape(n, 1)
print(f"weight: {weight}\nweight shape: {weight.shape}")
bias = 0.0

print("z = w * x + b")
z = np.dot(x, weight) + bias
print(f"z: {z}\nz shape{z.shape}")

y_pred = Pre(z)
print(f"ypred:\n{y_pred}\nypred: {y_pred.shape}")
y_pred = np.array(y_pred).reshape(y_pred.shape[0], 1)
print("e = y_pred - y")
error = y_pred - y
print(f"error:\n{error}\nerror shape: {error.shape}")

db = np.sum(error) / m
print(f"db:\n{db}\ndb shape: {db.shape}")

dw = np.sum(np.dot(x.T, error) / m)
print(f"dw:\n{dw}\ndw shape: {dw.shape}")

weight = np.array(weight).reshape(n, 1)
weight -= np.dot(dw, lr)
print(f"weight:\n{weight}\nshape: {weight.shape}")

bias = bias - lr * db
print(f"bias: {bias}")
print(50* "=")
print(f"weight:\n{weight}\nweight shape: {weight.shape}\nbias: {bias}")

In [9]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

print(x, x.shape)
print(y, y.shape)
print(50*"=")

#init
m, n = x.shape
lr = 0.001
print(f"m = {m}\nn = {n}")
P = lambda za: 1 / (1 + np.exp(-za))

bias = 0
weight = np.zeros(n)
weight = np.array(weight).reshape(n, 1)
print(f"weight:\n{weight}{weight.shape}")

print("#=======Z=======#")
z = np.dot(x, weight) + bias
print(f"z = weight * x + bias:\n{z}\nz shape: {z.shape}")

print("#=======Prob=======#")
ypred = P(z)
print(f"ypred:\n{ypred}{ypred.shape}")

print("#=======Error=======#")
error = ypred - y
print("error = ypred - y")
print(f"error:\n{error}{error.shape}")

print("#=======dw and db=======#")
print("sum(x * error) / m")
dw = np.dot(error.reshape(1, -1), x) / m
print("Error shape: ", error.shape)
print(f"dw: {dw}")

db = np.sum(error) / m
print(f"db: {db}")

print("============UPDATE===========")
weight = weight - (lr * dw.T)
bias = bias - (db * lr)
print(f"weight:\n{weight}")
print(f"weight shape:\n{weight.shape}")
print(f"bias: {bias}")

x = np.array([[90, 2]])
z = np.dot(x, weight) + bias
predict = P(z)
print(f"predict: {predict}")

[[ 90.  80.]
 [ 87.  30.]
 [100.  90.]
 [ 78.  90.]
 [ 75.  90.]
 [ 74.  60.]
 [ 70.  90.]
 [ 50.  98.]
 [ 20.  90.]] (9, 2)
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]] (9, 1)
m = 9
n = 2
weight:
[[0.]
 [0.]](2, 1)
#=======Z=======#
z = weight * x + bias:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
z shape: (9, 1)
#=======Prob=======#
ypred:
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]](9, 1)
#=======Error=======#
error = ypred - y
error:
[[-0.5]
 [ 0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]](9, 1)
#=======dw and db=======#
sum(x * error) / m
Error shape:  (9, 1)
dw: [[-2.33333333  1.        ]]
db: 0.05555555555555555
============UPDATE===========
weight:
[[ 0.00233333]
 [-0.001     ]]
weight shape:
(2, 1)
bias: -5.555555555555555e-05
predict: [[0.55179959]]


In [20]:
class LogisticRegression:
    def __init__(self):
        self.bias = 0.0
        self.weight = 0.0

    def train(self, x, y, epoch, lr):
        m = x.shape[0]
        self.n = x.shape[1]
        
        self.weight = np.zeros(n)
        self.weight = np.array(self.weight).reshape(n, 1)
        self.P = lambda za: 1 / (1 + np.exp(-za))
        
        for i in range(epoch):
            z = np.dot(x, self.weight) + self.bias
            y_pred = self.P(z)

            ypred = np.array(y_pred).reshape(m, 1)
            error = ypred - y
            error = error.reshape(1, -1)
        
            dw = np.dot(error, x) / m
            db = np.sum(error) / m
            
            self.weight = self.weight - (lr * dw.T)
            self.bias -= (db * lr)
            
    def predict(self, x):
        Z = np.dot(x, self.weight) + self.bias
        P = 1 / (1 + np.exp(-Z))
        return 1 if P >= 0.5 else 0 

In [24]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

modelLog = LogisticRegression()
modelLog.train(x=x, y=y, lr=0.001, epoch=30000)

print(f"Weight:\n{modelLog.weight}")
print(f"weight shape: {modelLog.weight.shape}")
print(f"Bias:{modelLog.bias}")

Weight:
[[ 0.02076474]
 [-0.02144339]]
weight shape: (2, 1)
Bias:-1.808193410130251


In [26]:
inp = np.array([[90, 1]])
ypred = modelLog.predict(inp)
print(ypred)

1


In [27]:
class LinearRegression:
    def __init__(self):
        self.bias = 0
        self.weight = 0

    def train(self, x, y, epoch, lr):
        self.P = lambda x: (self.weight * x) + self.bias
        m, n = x.shape
        self.weight = np.zeros(n)
        self.weight = np.array(self.weight).reshape(n, 1)
        
        for i in range(epoch):
            yPred = np.dot(x, self.weight) + self.bias
            ypred = np.array(y_pred).reshape(m, 1)
            error = yPred - Y
            error = error.reshape(1, -1)
            
            dw = (2/n) * np.dot(error, X)
            db = (2/n) * np.sum(error)
            
            self.weight = self.weight - (lr * dw.T)
            self.bias -= lr * db
            
    def predict(self, X, formula=False):
        ypred = self.P(X)
        return ypred