In [2]:
import numpy as np
import pandas as pd

print('import success')

import success


In [3]:
df = pd.read_csv('../data/logistic.csv')

Xdf = df[['score', 'attitude']]
Ydf = df['status']

X = np.array(Xdf).reshape(-1, 2).astype('float64')
Y = np.array(Ydf).reshape(-1, 1).astype('float64')

print('Dataset readed!')

Dataset readed!


In [4]:
print(Xdf)

   score  attitude
0     90        80
1     87        30
2    100        90
3     78        90
4     75        90
5     74        60
6     70        90
7     50        98
8     20        90


In [5]:
print(X, X.shape)

[[ 90.  80.]
 [ 87.  30.]
 [100.  90.]
 [ 78.  90.]
 [ 75.  90.]
 [ 74.  60.]
 [ 70.  90.]
 [ 50.  98.]
 [ 20.  90.]] (9, 2)


In [6]:
n = X.shape[1]
weight = np.ones(n)
print(weight, weight.shape)

[1. 1.] (2,)


In [7]:
arr = np.array([[2], [0]])
print(arr.shape)
print(arr)

(2, 1)
[[2]
 [0]]


In [8]:
weight = arr
multi = np.dot(X, weight)
print(multi)
print(multi.shape)

[[180.]
 [174.]
 [200.]
 [156.]
 [150.]
 [148.]
 [140.]
 [100.]
 [ 40.]]
(9, 1)


In [9]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

print(x, x.shape)
print(y, y.shape)

print(50* "=")
Pre = lambda za: 1 / (1 + np.exp(-za))
m, n = x.shape
print(f"m: {m}\nn: {n}")
lr = 0.0001

weight = np.zeros(n)
weight = np.array(weight).reshape(n, 1)
print(f"weight: {weight}\nweight shape: {weight.shape}")
bias = 0.0

print("z = w * x + b")
z = np.dot(x, weight) + bias
print(f"z: {z}\nz shape{z.shape}")

y_pred = Pre(z)
print(f"ypred:\n{y_pred}\nypred: {y_pred.shape}")
y_pred = np.array(y_pred).reshape(y_pred.shape[0], 1)
print("e = y_pred - y")
error = y_pred - y
print(f"error:\n{error}\nerror shape: {error.shape}")

db = np.sum(error) / m
print(f"db:\n{db}\ndb shape: {db.shape}")

dw = np.sum(np.dot(x.T, error) / m)
print(f"dw:\n{dw}\ndw shape: {dw.shape}")

weight = np.array(weight).reshape(n, 1)
weight -= np.dot(dw, lr)
print(f"weight:\n{weight}\nshape: {weight.shape}")

bias = bias - lr * db
print(f"bias: {bias}")
print(50* "=")
print(f"weight:\n{weight}\nweight shape: {weight.shape}\nbias: {bias}")

[[ 90.  80.]
 [ 87.  30.]
 [100.  90.]
 [ 78.  90.]
 [ 75.  90.]
 [ 74.  60.]
 [ 70.  90.]
 [ 50.  98.]
 [ 20.  90.]] (9, 2)
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]] (9, 1)
m: 9
n: 2
weight: [[0.]
 [0.]]
weight shape: (2, 1)
z = w * x + b
z: [[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
z shape(9, 1)
ypred:
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]
ypred: (9, 1)
e = y_pred - y
error:
[[-0.5]
 [ 0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
error shape: (9, 1)
db:
0.05555555555555555
db shape: ()
dw:
-1.3333333333333335
dw shape: ()
weight:
[[0.00013333]
 [0.00013333]]
shape: (2, 1)
bias: -5.555555555555556e-06
weight:
[[0.00013333]
 [0.00013333]]
weight shape: (2, 1)
bias: -5.555555555555556e-06


In [12]:
class LogisticRegression:
    def __init__(self):
        self.bias = 0.0
        self.weight = 0.0

    def train(self, x, y, epoch, lr):
        m, n = x.shape[0]
        self.n = x.shape[1]
        
        self.weight = np.zeros(n)
        self.weight = np.array(self.weight).reshape(n, 1)
        self.P = lambda za: 1 / (1 + np.exp(-za))
        
        for i in range(epoch):
            z = np.dot(x, self.weight) + self.bias
            y_pred = self.P(z)

            ypred = np.array(y_pred).reshape(m, 1)
            error = ypred - y
            error = error.reshape(1, -1)
        
            dw = np.dot(error, x) / m
            db = np.sum(error) / m
            
            self.weight = self.weight - (lr * dw.T)
            self.bias -= (db * lr)
            
    def predict(self, x):
        Z = np.dot(x, self.weight) + self.bias
        P = 1 / (1 + np.exp(-Z))
        return 1 if P >= 0.5 else 0

print('creating model done!')

creating model done!


In [13]:
print('system running...')
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

modelLog = LogisticRegression()
modelLog.train(x=x, y=y, lr=0.001, epoch=30000)

print(f"Weight:\n{modelLog.weight}")
print(f"weight shape: {modelLog.weight.shape}")
print(f"Bias:{modelLog.bias}")

system running...


TypeError: cannot unpack non-iterable int object

In [27]:
inp = np.array([[90, 1]])
ypred = modelLog.predict(inp)
print(ypred)

1


In [14]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

print(x, x.shape)
print(y, y.shape)
print(50*"=")

#init
m, n = x.shape
lr = 0.001
print(f"m = {m}\nn = {n}")
P = lambda za: 1 / (1 + np.exp(-za))

bias = 0
weight = np.zeros(n)
weight = np.array(weight).reshape(n, 1)
print(f"weight:\n{weight}{weight.shape}")

print("#=======Z=======#")
z = np.dot(x, weight) + bias
print(f"z = weight * x + bias:\n{z}\nz shape: {z.shape}")

print("#=======Prob=======#")
ypred = P(z)
print(f"ypred:\n{ypred}{ypred.shape}")

print("#=======Error=======#")
error = ypred - y
print("error = ypred - y")
print(f"error:\n{error}{error.shape}")

print("#=======dw and db=======#")
print("sum(x * error) / m")
dw = np.dot(error.reshape(1, -1), x) / m
print("Error shape: ", error.shape)
print(f"dw: {dw}")

db = np.sum(error) / m
print(f"db: {db}")

print("============UPDATE===========")
weight = weight - (lr * dw.T)
bias = bias - (db * lr)
print(f"weight:\n{weight}")
print(f"weight shape:\n{weight.shape}")
print(f"bias: {bias}")

x = np.array([[90, 2]])
z = np.dot(x, weight) + bias
predict = P(z)
print(f"predict: {predict}")

[[ 90.  80.]
 [ 87.  30.]
 [100.  90.]
 [ 78.  90.]
 [ 75.  90.]
 [ 74.  60.]
 [ 70.  90.]
 [ 50.  98.]
 [ 20.  90.]] (9, 2)
[[1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]] (9, 1)
m = 9
n = 2
weight:
[[0.]
 [0.]](2, 1)
#=======Z=======#
z = weight * x + bias:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
z shape: (9, 1)
#=======Prob=======#
ypred:
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]](9, 1)
#=======Error=======#
error = ypred - y
error:
[[-0.5]
 [ 0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]](9, 1)
#=======dw and db=======#
sum(x * error) / m
Error shape:  (9, 1)
dw: [[-2.33333333  1.        ]]
db: 0.05555555555555555
============UPDATE===========
weight:
[[ 0.00233333]
 [-0.001     ]]
weight shape:
(2, 1)
bias: -5.555555555555555e-05
predict: [[0.55179959]]


In [25]:
class LogisticRegression:
    def __init__(self):
        self.bias = 0.0
        self.weight = 0.0

    def train(self, x, y, epoch, lr):
        m = x.shape[0]
        self.n = x.shape[1]
        
        self.weight = np.zeros(self.n)
        self.weight = np.array(self.weight).reshape(self.n, 1)
        self.P = lambda za: 1 / (1 + np.exp(-za))
        
        for i in range(epoch):
            z = np.dot(x, self.weight) + self.bias
            y_pred = self.P(z)

            ypred = np.array(y_pred).reshape(m, 1)
            error = ypred - y
            error = error.reshape(1, -1)
        
            dw = np.dot(error, x) / m
            db = np.sum(error) / m
            
            self.weight = self.weight - (lr * dw.T)
            self.bias -= (db * lr)
            
    def predict(self, x):
        Z = np.dot(x, self.weight) + self.bias
        P = 1 / (1 + np.exp(-Z))
        return 1 if P >= 0.5 else 0

In [15]:
%load_ext Cython

In [25]:
%%cython -a
import cython
import numpy as np
cimport numpy as np

@cython.boundscheck(False)
@cython.wraparound(False)
@cython.cdivision(True)

cdef class LogisticRegressionC:
    cdef public double bias
    cdef public double[:] weight
    cdef int n

    def __init__(self):
        self.bias = 0.0

    property weight_arr:
        def __get__(self):
            return np.asarray(self.weight)

    cpdef void fit(self, double[:, :] x, double[:, :] y, int epoch, double lr):
        cdef int m = x.shape[0]
        self.n = x.shape[1]
        self.weight = np.zeros(self.n, dtype=np.float64)
        
        cdef int i, j, k
        cdef double[:] y_pred = np.zeros(m, dtype=np.float64)
        cdef double z, error_i, db, dw_j

        for i in range(epoch):
            db = 0.0
            dw = np.zeros(self.n, dtype=np.float64)
            
            for j in range(m):
                z = 0.0
                for k in range(self.n):
                    z += x[j, k] * self.weight[k]
                z += self.bias
                
                y_pred[j] = 1.0 / (1.0 + np.exp(-z))
                error_i = y_pred[j] - y[j, 0]
                
                db += error_i
                for k in range(self.n):
                    dw[k] += error_i * x[j, k]
            
            self.bias -= (lr * db / m)
            for k in range(self.n):
                self.weight[k] -= (lr * dw[k] / m)

    cpdef long long[:] predict(self, long long[:, :] x):
        cdef int m = x.shape[0]  
        cdef int n = x.shape[1]
        cdef long long[:] pred = np.zeros(m, dtype=np.int64)
        
        cdef int i, j
        cdef double z, p
    
        for i in range(m):
            z = 0.0
            for j in range(n):
                z += x[i, j] * self.weight[j]
            z += self.bias
            
            p = 1.0 / (1.0 + np.exp(-z))
            pred[i] = 1 if p >= 0.5 else 0
            
        return np.asarray(pred)

In [18]:
Xdf = df[['score', 'attitude']]
Ydf = df['status']

x = np.array(Xdf).reshape(-1, 2).astype('float64')
y = np.array(Ydf).reshape(-1, 1).astype('float64')

modelLog = LogisticRegressionC()
modelLog.fit(x=x, y=y, lr=0.009, epoch=30000)

print(f"Weight:\n{modelLog.weight_arr}")
print(f"weight shape: {modelLog.weight.shape}")
print(f"Bias:{modelLog.bias}")

arr = np.array([[90, 1]])
ypred = modelLog.predict(arr)
print(f"ypred: {np.asarray(ypred)}")

Weight:
[ 0.30177631 -0.25197465]
weight shape: (2,)
Bias:-17.72532660412913
ypred: [1]


In [38]:
df = pd.read_csv('../data/StudentPerformance.csv')

x = df[['Hours Studied', 'Sleep Hours', 'Sample Question Papers Practiced']]
y = df['Performance Index']

x = np.array(x).reshape(-1, 3).astype('float64')
y = np.array(y).reshape(-1, 1).astype('float64')

print("dataset readed!")

dataset readed!


In [26]:
print('system running...')
model = LogisticRegressionC()
model.fit(x=x, y=y, lr=0.001, epoch=1000)

print(f"Weight:\n{model.weight_arr}")
print(f"weight shape: {model.weight.shape}")
print(f"Bias:{model.bias}")

arr = np.array([[90, 80, 23]])
ypred = model.predict(arr)
print(f"predicting: {arr} \nypred: {np.asarray(ypred)}")

system running...
Weight:
[289.33174006 355.69104094 250.91422739]
weight shape: (3,)
Bias:54.22531365586153
predicting: [[90 80 23]] 
ypred: [1]


In [55]:
%%cython -a
import cython
import numpy as np
cimport numpy as np

@cython.boundscheck(False)
@cython.wraparound(False)
@cython.cdivision(True)

cdef class CLinearROLS:
    cdef public double[:] weight
    cdef public double bias
    
    def __init__(self):
        self.bias = 0.0

    property weight_arr:
        def __get__(self):
            return np.asarray(self.weight)
    
    cpdef void fit(self, double[:, :] X, double[:, :] Y):
        cdef double sigmaX=0.0, sigmaY=0.0, sigmaXS=0.0, sigmaXY=0.0
    
        cdef int i, n, m
        n = X.shape[0]
        m = X.shape[1]

        self.weight = np.zeros(m, dtype=np.float64)

        for i in range(n):
            sigmaY += Y[i, 0]
            for j in range(m):
                sigmaXS += X[i, j] ** 2
                sigmaX += X[i, j]
                sigmaXY += X[i, j] * Y[i, 0]

        cdef double denom = (n * sigmaXS) - (sigmaX ** 2)
        for i in range(m):
            if denom != 0:
                self.weight[j] = ((n * sigmaXY) - (sigmaX * sigmaY)) / denom
        
        self.bias = (sigmaY - (self.weight[0] * sigmaX)) / n 

    cpdef double[:] predict(self, long long[:, :] X):
        cdef int i, j, n, m
        n = X.shape[0]
        m = X.shape[1]
        cdef double[:] yPred = np.zeros(n, dtype=np.float64)

        for i in range(n):
            yPred[i] = self.bias
            for j in range(m):
                yPred[i] += self.weight[j] * X[i, j]
        return yPred

Content of stdout:
_cython_magic_72931fde388615ae0a84723a9e2f3a91e10d9b5d04735c1d1afda71f03cc5711.c
C:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\include\numpy\npy_1_7_deprecated_api.h(14) : Warning Msg: Using deprecated NumPy API, disable it with #define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION
C:\Users\Lenovo\.ipython\cython\_cython_magic_72931fde388615ae0a84723a9e2f3a91e10d9b5d04735c1d1afda71f03cc5711.c(19106): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\Lenovo\.ipython\cython\_cython_magic_72931fde388615ae0a84723a9e2f3a91e10d9b5d04735c1d1afda71f03cc5711.c(19115): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\Lenovo\.ipython\cython\_cython_magic_72931fde388615ae0a84723a9e2f3a91e10d9b5d04735c1d1afda71f03cc5711.c(19574): warning C4244: '=': conversion from 'Py_ssize_t' to 'int', possible loss of data
C:\Users\Lenovo\.ipython\cython\_cython_magic_72931fde38

In [56]:
df = pd.read_csv('../data/StudentPerformance.csv')

x = df[['Hours Studied', 'Sleep Hours', 'Sample Question Papers Practiced']]
y = df['Performance Index']

x = np.array(x).reshape(-1, 3).astype('float64')
y = np.array(y).reshape(-1, 1).astype('float64')
print("dataset readed!")

print('training...')
model = CLinearROLS()
model.fit(X=x, Y=y)

print(f"Weight:\n{model.weight_arr}")
print(f"weight shape: {model.weight.shape}")
print(f"Bias:{model.bias}")

dataset readed!
training...
Weight:
[ 0.          0.         -0.14728288]
weight shape: (3,)
Bias:55.2248


In [58]:
arr = np.array([[90, 99, 87]])
ypred = model.predict(arr)
print(f"predicting: {arr} \nypred: {np.asarray(ypred)}")

predicting: [[90 99 87]] 
ypred: [42.4111895]
