In [1]:
import pandas as pd
import numpy as np

In [2]:
def splitData(x, y, test_size, random_state):
    n = int(len(x) * test_size)
    x_test = x.sample(frac=test_size, random_state=random_state)
    y_test = y.sample(frac=test_size, random_state=random_state)
    x_train = x.drop(x_test.index)
    y_train = y.drop(y_test.index)

    return x_train, y_train, x_test, y_test

dfLinear = pd.read_csv('../data/linear.csv')

x1 = dfLinear['ps']
y1 = dfLinear['fs']

print(dfLinear)

    ps  fs
0   90  93
1   87  88
2  100  98
3   78  78
4   75  76
5   74  76
6   70  69
7   50  60
8   20  10
9   12  10


In [5]:
x_train, y_train, x_test, y_test = splitData(
    x1, y1, test_size=0.2, random_state=1)

print(x_train)
print(y_train)
print(x_test)
print(y_test)

0    90
1    87
3    78
4    75
5    74
6    70
7    50
8    20
Name: ps, dtype: int64
0    93
1    88
3    78
4    76
5    76
6    69
7    60
8    10
Name: fs, dtype: int64
2    100
9     12
Name: ps, dtype: int64
2    98
9    10
Name: fs, dtype: int64


In [6]:
dfLogistic = pd.read_csv('../data/logistic.csv')

X = dfLogistic['value']
Y = dfLogistic['status']

x = np.array(X).reshape(-1, 1)
y = np.array(Y).reshape(-1, 1)
w = 0
b = 0
lr = 0.001
m = len(X)

print(50*"=")
print(f"w = {w}")
print(f"b = {b}")
print(f"lr = {lr}")
print(f"m = {m}")
print(50*"=")

z = (w * x) + b
print(f"z =\n{z}")
prob = 1 / (1 + np.exp(-z))
print(f"Probabillity =\n{prob}")
error = prob - y
print(f"Error = \n{error}")
db = np.sum(error) / m
print(f"db = {db}")
dw = np.sum(x * error) / m
print(f"dw = {dw}")
w = w - (lr * dw)
b = b - (lr * db)
print(f"w = {w}")
print(f"b = {b}")

w = 0
b = 0
lr = 0.001
m = 9
z =
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]
Probabillity =
[[0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]
 [0.5]]
Error = 
[[-0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [-0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]
 [ 0.5]]
db = -0.05555555555555555
dw = -12.0
w = 0.012
b = 5.555555555555555e-05


In [ ]:
class LogisticRegression:
    def __init__(self, x, y):
        self.bias = 0.0
        self.weight = 0.0
        self.x = np.array(x).reshape(-1, 1)
        self.y = np.array(y).reshape(-1, 1)
        
    def train(self, maxIter, lr, tol):
        m = len(self.x)
        self.P = lambda za: 1 / (1 + np.exp(-za))
        lossB = np.inf
        for i in range(maxIter):
            z = self.weight * self.x + self.bias
            yPred = self.P(z)
            yPred = np.clip(yPred, 1e-15, 1 - 1e-15)
            
            lossN = -(1/m) * np.sum(self.y * np.log(yPred) + (1 - self.y) * np.log(1 - yPred))
            
            if abs(lossB - lossN) < tol:
                print(f"Convergen at iteration-{i}")
                break
            
            lossB = lossN
            
            error = yPred - self.y
            dw = np.sum(self.x * error) / m
            db = np.sum(error) / m

            self.weight -= lr * dw
            self.bias -= lr * db
                
        return self.weight, self.bias
    
    def predict(self, x):
        z = self.weight * x + self.bias
        P = self.P(z)
        return P

dfLogistic = pd.read_csv('../data/logistic.csv')

X = dfLogistic['value']
Y = dfLogistic['status']

model = LogisticRegression(X, Y)
weight, bias = model.train(lr=0.001, maxIter=70000, tol=1e-6)
print(f"weight: {weight}\nbias: {bias}")

input = np.array([10, 20, 30, 40, 50, 60, 70, 74, 75, 80, 90, 100])
for n in input:
    ypred = round(model.predict(n).item(), 3)
    if ypred >= 0.5:
        ypred = 1
    else:
        ypred = 0
    print(f"Input {n}:\nPredict: {ypred}")

In [9]:
class OLS:
    def __init__(self):
        self.bias = 0
        self.weight = 0

    def train(self, x, y):
        X = np.array(x).reshape(-1, 1)
        Y = np.array(y).reshape(-1, 1)
        print(f"X:\n{X}\nY:\n{Y}")
        xSquare = x ** 2
        print("XS", xSquare)
        XY = X * Y
        print("XY", XY)
        sigmaX = np.sum(X)
        print("sigmaX", sigmaX)
        sigmaY = np.sum(Y)
        print("sigmaY, ", sigmaY)
        sigmaXS = np.sum(xSquare)
        print("sigmaXS", sigmaXS)
        sigmaXY = np.sum(XY)
        print("sigmaXY", sigmaXY)
        n = len(X)
        print(n)
        self.weight = ((n * sigmaXY) - (sigmaX * sigmaY)) / ((n * sigmaXS) - sigmaX ** 2)
        self.bias = (sigmaY - (self.weight * sigmaX)) / n 

        return self.weight, self.bias
        
    def predict(self, X):
        yp = self.bias + (self.weight * X)
        return yp



x_train1, y_train1, x_test1, y_test1 = splitData(
    x, y, test_size=0.2, random_state=1)

print("=====Splitting Success=====")
print(x_train1, "\n", y_train1)

x = [1, 2, 3]
y = [2, 4, 5]
df = pd.DataFrame(list(zip(x, y)), columns=["values", "targets"])
x = df['values']
y = df['targets']

modelLin = OLS()
weightLin, biasLin = modelLin.train(x=x, y=y)
print(f"Weight:\n{weightLin}")
print(f"Bias:\n{biasLin}\n")

ypred = modelLin.predict(80)
print(f"yPred: {ypred}")

AttributeError: 'numpy.ndarray' object has no attribute 'sample'